# Generated by Django 6.0.3 on 2026-03-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrador'), ('GERENTE', 'Gerente de Proyecto'), ('ASESOR', 'Asesor Comercial'), ('ANALISTA_CREDITO', 'Analista de Crédito'), ('JEFE_OBRA', 'Jefe de Obra'), ('DEMO_GUEST', 'Invitado Demo')], default='DEMO_GUEST', help_text='Rol principal del usuario en la plataforma.', max_length=20),
        ),
    ]
