# Generated by Django 6.0.3 on 2026-03-19 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Habitaciones, Baños, Área m2, Parqueadero', max_length=50)),
                ('data_type', models.CharField(choices=[('NUMBER', 'Número'), ('BOOLEAN', 'Sí/No'), ('TEXT', 'Texto Libre')], default='NUMBER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='POICategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Parques, Supermercados', max_length=50)),
                ('icon_identifier', models.CharField(blank=True, help_text="Clave para el frontend (ej: 'icon-park', 'icon-mall')", max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del proyecto de obra nueva', max_length=150)),
                ('status', models.CharField(choices=[('PLANNING', 'En Planos'), ('CONSTRUCTION', 'En Construcción'), ('DELIVERED', 'Entregado')], default='PLANNING', max_length=20)),
                ('is_demo', models.BooleanField(default=False, help_text='Si es True, este proyecto lo verá el rol Invitado Demo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Centro Comercial Hayuelos', max_length=100)),
                ('travel_mode', models.CharField(choices=[('WALKING', 'Caminando'), ('DRIVING', 'Carro'), ('BIKING', 'Bicicleta'), ('TRANSIT', 'Transporte Público')], default='WALKING', max_length=20)),
                ('time_in_minutes', models.IntegerField(help_text='Tiempo de desplazamiento en minutos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pois', to='catalogue.poicategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='catalogue.project')),
            ],
            options={
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['category__name', 'time_in_minutes'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartamento'), ('HOUSE', 'Casa'), ('COMMERCIAL', 'Local Comercial'), ('RURAL_LOT', 'Lote Campestre')], default='APARTMENT', max_length=20)),
                ('property_name', models.CharField(help_text='Ej: Apt 402, Local 1', max_length=50)),
                ('tower_or_block', models.CharField(blank=True, help_text='Ej: Torre 1, Manzana B, Interior 3', max_length=50, null=True)),
                ('floor_number', models.IntegerField(blank=True, help_text='Piso o Nivel. Ej: 4 (Útil para precios escalonados)', null=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Precio base sin acabados extra', max_digits=12)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido')], default='AVAILABLE', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='catalogue.project')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(help_text="El valor real. Ej: '3' para habitaciones, 'True' para parqueadero", max_length=100)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogue.featurecatalog')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalogue.property')),
            ],
            options={
                'unique_together': {('property', 'feature')},
            },
        ),
    ]
