# Generated by Django 6.0.3 on 2026-03-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Dirección o sector del proyecto. Ej: Calle 80 con Av. Boyacá, Bogotá', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservado'), ('SOLD', 'Vendido'), ('BUILDING', 'En Construcción'), ('DELIVERED', 'Entregado')], default='AVAILABLE', max_length=20),
        ),
    ]
