# Generated by Django 6.0.3 on 2026-03-26 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_remove_document_file_url_client_identification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Crédito Hipotecario VIS, Leasing No VIS', max_length=150, verbose_name='Nombre del Producto')),
                ('amortization_type', models.CharField(choices=[('FRANCESA', 'Francesa (cuota fija)'), ('ALEMANA', 'Alemana (capital fijo)')], default='FRANCESA', help_text='Francesa: cuota total fija. Alemana: capital fijo, cuota decrece.', max_length=10, verbose_name='Tipo de Amortización')),
                ('nominal_rate', models.DecimalField(decimal_places=2, help_text='Ej: 12.50 para una tasa del 12.5% anual', max_digits=5, verbose_name='Tasa Nominal Anual (%)')),
                ('min_term_months', models.IntegerField(help_text='Ej: 60 meses = 5 años', verbose_name='Plazo mínimo (meses)')),
                ('max_term_months', models.IntegerField(help_text='Ej: 360 meses = 30 años', verbose_name='Plazo máximo (meses)')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto mínimo del crédito')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto máximo del crédito')),
                ('max_quota_income_ratio', models.DecimalField(decimal_places=2, default=30.0, help_text='Límite de la cuota sobre el ingreso. Ej: 30.00 = la cuota no puede superar el 30% del salario.', max_digits=5, verbose_name='Relación máxima cuota/ingreso (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Solo los productos activos aparecen en el simulador.', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto de Crédito',
                'verbose_name_plural': '1. Productos de Crédito',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor del crédito en pesos. Generalmente = precio_base - cuota_inicial.', max_digits=14, verbose_name='Monto Solicitado')),
                ('term_months', models.IntegerField(help_text='Número de meses para pagar. Ej: 180 = 15 años.', verbose_name='Plazo (meses)')),
                ('status', models.CharField(choices=[('RADICADA', 'Radicada'), ('EN_ESTUDIO', 'En Estudio'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('DESEMBOLSADA', 'Desembolsada')], default='RADICADA', max_length=20, verbose_name='Estado de la Solicitud')),
                ('credit_score', models.IntegerField(blank=True, help_text='Score calculado por el motor dummy (0-1000).', null=True, verbose_name='Score Crediticio')),
                ('rejection_reason', models.TextField(blank=True, help_text='Obligatorio si el estado es RECHAZADA.', null=True, verbose_name='Motivo de Rechazo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(help_text='La oportunidad del CRM que originó esta solicitud.', on_delete=django.db.models.deletion.PROTECT, related_name='loan_application', to='crm.opportunity', verbose_name='Oportunidad de Venta')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Analista de crédito que tomó la decisión final.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loanflow.loanproduct', verbose_name='Producto de Crédito')),
            ],
            options={
                'verbose_name': 'Solicitud de Crédito',
                'verbose_name_plural': '2. Solicitudes de Crédito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(help_text='Estado desde el que se hizo la transición.', max_length=20, verbose_name='Estado Anterior')),
                ('to_status', models.CharField(help_text='Estado al que se transitó.', max_length=20, verbose_name='Estado Nuevo')),
                ('notes', models.TextField(blank=True, help_text='Observaciones del analista o descripción automática del evento.', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='loanflow.loanapplication', verbose_name='Solicitud de Crédito')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la transición. Null si fue el sistema automáticamente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': '4. Historial de Estados',
                'ordering': ['application', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.PositiveIntegerField(verbose_name='Número de Cuota')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('principal', models.DecimalField(decimal_places=2, help_text='Porción de la cuota que reduce el saldo del crédito.', max_digits=14, verbose_name='Abono a Capital')),
                ('interest', models.DecimalField(decimal_places=2, help_text='Porción de la cuota que corresponde a intereses del período.', max_digits=14, verbose_name='Intereses')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Capital pendiente de pago después de esta cuota.', max_digits=14, verbose_name='Saldo Pendiente')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Se registra cuando el cliente paga. Null = pendiente de pago.', null=True, verbose_name='Fecha de Pago')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedule', to='loanflow.loanapplication', verbose_name='Solicitud de Crédito')),
            ],
            options={
                'verbose_name': 'Cuota de Amortización',
                'verbose_name_plural': '3. Tabla de Amortización',
                'ordering': ['application', 'period'],
                'unique_together': {('application', 'period')},
            },
        ),
    ]
