# Generated by Django 6.0.3 on 2026-03-19 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('lead_source', models.CharField(choices=[('FACEBOOK', 'Campaña Facebook'), ('WALK_IN', 'Sala de Ventas'), ('REFERRAL', 'Referido'), ('WEBSITE', 'Sitio Web')], default='WEBSITE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente Comercial',
                'verbose_name_plural': 'Clientes Comerciales',
            },
        ),
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_income', models.DecimalField(decimal_places=2, help_text='Ingresos mensuales demostrables', max_digits=12)),
                ('initial_savings', models.DecimalField(decimal_places=2, help_text='Ahorro disponible para la cuota inicial', max_digits=12)),
                ('has_debts', models.BooleanField(default=False, help_text='¿Tiene reportes o deudas altas?')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('1_LEAD', '1. Captación (Lead)'), ('2_QUALIFYING', '2. Perfilamiento'), ('3_RESERVATION', '3. Separación (Reserva)'), ('4_DOCUMENTS', '4. Gestión de Documentos'), ('5_PRE_APPROVED', '5. Pre-Aprobación Bancaria'), ('6_PROMISE', '6. Promesa de Compraventa'), ('7_FINAL_APPROVAL', '7. Aprobación y Escrituración'), ('8_DELIVERED', '8. Entrega'), ('LOST', 'Perdido / Rechazado')], default='1_LEAD', max_length=20)),
                ('dummy_bank_score', models.IntegerField(blank=True, help_text='Puntaje generado por el motor de simulación (0-1000)', null=True)),
                ('is_pre_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_opportunities', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.client')),
                ('property_of_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='catalogue.property')),
            ],
            options={
                'verbose_name': 'Oportunidad de Venta',
                'verbose_name_plural': 'Oportunidades de Vent',
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Reunión Presencial / Sala de Ventas'), ('SYSTEM_NOTE', 'Nota del Sistema')], default='WHATSAPP', max_length=20)),
                ('notes', models.TextField(help_text='Resumen de lo que se habló con el cliente')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.opportunity')),
            ],
            options={
                'verbose_name': 'Registro de Interacción',
                'verbose_name_plural': 'Registros de Interacciones',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_CARD', 'Cédula de Ciudadanía'), ('BANK_STATEMENT', 'Extractos Bancarios (3 meses)'), ('PAY_STUB', 'Desprendibles de Nómina'), ('TAX_RETURN', 'Declaración de Renta'), ('PROMISE_CONTRACT', 'Promesa de Compraventa Firmada')], max_length=30)),
                ('file_url', models.URLField(blank=True, help_text='URL del archivo en el Storage (AWS S3, etc.)', max_length=500, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado / Ilegible')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.opportunity')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_fee', models.DecimalField(decimal_places=2, help_text='Dinero dado para separar el inmueble', max_digits=12)),
                ('reservation_date', models.DateField(blank=True, null=True)),
                ('down_payment_total', models.DecimalField(decimal_places=2, help_text='Total de la cuota inicial (ej: 30%)', max_digits=12)),
                ('monthly_installments', models.IntegerField(default=1, help_text='Número de meses para pagar la cuota inicial')),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Valor de la cuota mensual', max_digits=12)),
                ('is_signed', models.BooleanField(default=False, help_text='¿Ya firmaron la Promesa de Compraventa?')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='crm.opportunity')),
            ],
            options={
                'verbose_name': 'Plan de Pagos',
                'verbose_name_plural': 'Planes de Pagos',
            },
        ),
    ]
