# Generated by Django 6.0.3 on 2026-03-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
        migrations.AddField(
            model_name='client',
            name='identification',
            field=models.CharField(blank=True, help_text='Número de cédula o documento de identidad', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='s3_key',
            field=models.CharField(blank=True, help_text='Ruta del objeto en AWS S3. Ej: documents/clients/{uuid}/cedula.pdf', max_length=500, null=True),
        ),
    ]
