# Generated by Django 6.0.3 on 2026-03-19 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Ej: MUR-01, EXC-05', max_length=20, unique=True, verbose_name='Código A.P.U.')),
                ('name', models.CharField(help_text='Ej: Muro en ladrillo prensado a la vista', max_length=200, verbose_name='Nombre de la Actividad')),
                ('unit_of_measure', models.CharField(choices=[('M2', 'Metro Cuadrado (m2)'), ('M3', 'Metro Cúbico (m3)'), ('ML', 'Metro Lineal (ml)'), ('UND', 'Unidad (und)'), ('GL', 'Global (gl)')], default='M2', max_length=10, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Actividad (A.P.U.)',
                'verbose_name_plural': '2. Actividades (A.P.U.)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Cemento Gris, Oficial de Construcción, Mezcladora', max_length=200, verbose_name='Nombre del Insumo')),
                ('resource_type', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Mano de Obra'), ('EQUIPMENT', 'Equipo / Herramienta')], max_length=20, verbose_name='Tipo de Recurso')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogramo (kg)'), ('TON', 'Tonelada (ton)'), ('M3', 'Metro Cúbico (m3)'), ('M2', 'Metro Cuadrado (m2)'), ('ML', 'Metro Lineal (ml)'), ('UND', 'Unidad (und)'), ('BAG', 'Bulto (50kg)'), ('HOUR', 'Hora (hr)'), ('DAY', 'Día (dia)'), ('GL', 'Galón (gl)')], max_length=10, verbose_name='Unidad de Medida')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Costo base sin impuestos', max_digits=12, verbose_name='Costo Unitario ($)')),
            ],
            options={
                'verbose_name': 'Recurso / Insumo',
                'verbose_name_plural': '1. Recursos e Insumos',
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: Torre 1 - Cimentación', max_length=100, verbose_name='Nombre de la Fase')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio Estimada')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='catalogue.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Fase del Proyecto',
                'verbose_name_plural': '3. Fases de Obra',
                'ordering': ['project', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TODO', 'Por Hacer'), ('IN_PROGRESS', 'En Progreso'), ('REVIEW', 'En Revisión / Calidad'), ('DONE', 'Terminada')], default='TODO', max_length=20, verbose_name='Estado Kanban')),
                ('planned_quantity', models.DecimalField(decimal_places=2, help_text='Cuánto se mandó a hacer. Ej: 50 (m2)', max_digits=12, verbose_name='Cantidad Planeada')),
                ('executed_quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Cuánto lleva hecho el contratista', max_digits=12, verbose_name='Cantidad Ejecutada')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='construction.activity', verbose_name='Actividad (A.P.U.) a ejecutar')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='construction.projectphase', verbose_name='Fase de la Obra')),
            ],
            options={
                'verbose_name': 'Tarea (Kanban)',
                'verbose_name_plural': '4. Tareas (Kanban)',
            },
        ),
        migrations.CreateModel(
            name='TaskConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad Real Usada')),
                ('date_reported', models.DateField(auto_now_add=True, verbose_name='Fecha del Reporte')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='construction.resource', verbose_name='Insumo Gastado')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='construction.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Reporte de Consumo',
                'verbose_name_plural': '5. Consumos Reales',
            },
        ),
        migrations.CreateModel(
            name='APUDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Cuánto se usa para 1 unidad de obra', max_digits=12, verbose_name='Cantidad Unitaria')),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Ej: 5.00 para 5% de rotura/pérdida', max_digits=5, verbose_name='% Desperdicio')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='construction.activity', verbose_name='Actividad')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='apu_usages', to='construction.resource', verbose_name='Recurso / Insumo')),
            ],
            options={
                'verbose_name': 'Detalle de Insumo',
                'verbose_name_plural': 'Detalles del A.P.U.',
                'unique_together': {('activity', 'resource')},
            },
        ),
    ]
