# Generated by Django 6.0.3 on 2026-03-26 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_project_location_alter_property_status'),
        ('construction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada')], default='PENDING', max_length=20, verbose_name='Estado de la Fase'),
        ),
        migrations.AddField(
            model_name='task',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Apartamento o local que se está construyendo. Vacío si es área común.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_tasks', to='catalogue.property', verbose_name='Unidad del Proyecto'),
        ),
        migrations.AddField(
            model_name='taskconsumption',
            name='logged_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró este consumo real.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
    ]
